---
- name: deploy test web applicaiton
  hosts: all
  become: True
  pre_tasks:
    - name: install sudo
      dnf:
        name:
        - sudo
        state: present
    - name: install the java-1.8.0-openjdk and devel packages
      dnf:
        name: 
        - java-1.8.0-openjdk
        - java-1.8.0-openjdk-devel
        state: present
  tasks:
    - name: checkout remote git
      git:
        repo: 'https://github.com/tom721/freelec-springboot2-webservice'
        dest: /tmp/freelec-springboot2-webservice
        force: yes

    - name: change mod for gradlew file to execution
      shell: chmod +x gradlew
      args:
        chdir: /tmp/freelec-springboot2-webservice

    - name: build with gradle
      shell: ./gradlew build
      args:
        chdir: /tmp/freelec-springboot2-webservice
  
    - name: run web application with java
      shell: java -jar build/libs/freelec-springboot2-webservice-1.0-SNAPSHOT.jar &
      args:
        executable: "/bin/bash"
        chdir: /tmp/freelec-springboot2-webservice

