---
- name: deploy test web applicaiton
  hosts: all
  become: True
  pre_tasks:
    - name: install the java-1.8.0-openjdk and devel packages
      dnf:
        name: 
        - java-1.8.0-openjdk
        - java-1.8.0-openjdk-devel
        state: present
  tasks:
    - name: download jar file for application from web
      get_url:
        url: http://192.168.6.171:32000/repository/maven-snapshots/com/springboot/example/freelec-springboot2-webservice/1.0-SNAPSHOT/freelec-springboot2-webservice-1.0-20210426.071405-1.jar
        dest: /tmp/freelec-springboot2-webservice.jar
  
    - name: run web application with java
      shell: java -jar freelec-springboot2-webservice.jar </dev/null >/dev/null 2>&1 &
      poll: 0
      args:
        chdir: /tmp/

